name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

    - name: List test files
      run: |
        echo "Current directory: $(pwd)"
        echo "Listing files in ccrust/tests/files:"
        ls -R ccrust/tests/files || echo "Test files directory not found"

    - name: Run tests
      run: cargo test --verbose
